version: '3.9'

services:

  api:
    image: cheshtnut/saqartvel-DRF:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    restart: always
    environment:
      DB_HOST: postgres
    volumes:
      - ./Saqartvel/:/app
      - ./.envs:/app/.env
    env_file:
      - /app/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8000'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg_data:/var/lib/postgresql/data