name: Build and deploy
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker build and push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/saqartvel-drf:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/saqartvel-drf:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: anthonykgross/ansible-vault-cli-github-action@v1
        with:
          vault_key: ${{ secrets.VAULT_KEY }}
          command: 'ansible-vault decrypt deploy/.env'
      - name: Render configs
        run: |
          if [ ! -d "deploy" ]; then
            mkdir deploy
          fi
          cat docker-compose.yaml | envsubst > deploy/docker-compose.yaml
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "deploy/docker-compose.yaml,deploy/.env"
          target: app
          strip_components: 1
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd app
            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d