name: Build and deploy
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Docker build and push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/saqartvel-drf:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/saqartvel-drf:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  eploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Decrypt .env file
        run: |
          echo "${{ secrets.VAULT_KEY }}" | ansible-vault decrypt deploy/.env --output=deploy/.env.decrypted
      - name: Render configs
        run: |
          if [ ! -d "deploy" ]; then
            mkdir deploy
          fi
          cat docker-compose.yaml | envsubst > deploy/docker-compose.yaml
      - name: Copy files to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PASSWORD }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          scp -o StrictHostKeyChecking=no -i ssh_key deploy/docker-compose.yaml deploy/.env.decrypted ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/app
      - name: Deploy app
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /app && docker-compose up -d"