name: Build and deploy
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/saqartvel-drf:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/saqartvel-drf:$GITHUB_REF_NAME-$GITHUB_RUN_ID


  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: anthonykgross/ansible-vault-cli-github-action@v1
        with:
          vault_key: ${{ secrets.VAULT_KEY }}
          command: 'ansible-vault decrypt deploy/.env'
      - name: Update compose
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          envsubst '$DOCKER_USERNAME' < deploy/docker-compose.yaml > deploy/tmp.docker-compose.yaml
          mv deploy/tmp.docker-compose.yaml deploy/docker-compose.yaml
      - name: Copy on server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: 'deploy/*'
          target: app
          strip_components: 1
      - name: Run compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd app
            docker system prune
            docker-compose pull
            docker-compose up -d

