# Generated by Django 4.2.9 on 2024-01-25 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_subcategory_category_alter_venue_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
