# Generated by Django 4.2.9 on 2024-01-25 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_venue_slug_alter_venue_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='images',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='telephone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
