# Generated by Django 4.2.9 on 2024-02-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
