# Generated by Django 4.2.9 on 2024-02-10 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_venue_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('url', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.RemoveField(
            model_name='venue',
            name='images',
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='venue',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.image'),
        ),
    ]
