# Generated by Django 4.2.9 on 2024-02-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_image_alter_category_slug_alter_subcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
